version: '3'
services:
  warehouse:
    container_name: warehouse_node
    restart: always
    build: .
    # image: lomkovsky/warehouse_node
    ports:
      - '80:3000'
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongo_data:/data/db
    ports:
      - '27017:27017'
    restart: always
    